version: "3"

networks:
  api-net:
    driver: bridge

volumes:
  mongo_volume:

services:
  api:
    image: igorcruz/fastapi:v1.1
    container_name: api
    ports:
      - 80:80
    networks:
      - api-net
    environment:
      MONGODB_URI: $MONGODB_URI

  mongo_exporter:
    image: percona/mongodb_exporter:0.30.0
    container_name: mongo-exporter
    depends_on:
      - api
    ports:
      - 9216:9216
    networks:
      - api-net
    environment:
      MONGODB_URI: $MONGODB_URI

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    depends_on:
      - mongo_exporter
    privileged: true
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090
    networks:
      - api-net
  
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    depends_on:
      - prometheus
    ports:
      - "3000:3000"
    networks:
      - api-net